Figuring out the time periods for each variable in the algorithm-:
Those with pre-initialized beginnings-:
mu
pi
L
w


The variables whose end should be at nl or nl-1 during iteration not nl+1-:
mu- end at nl

In [1]:
nl = 100 # time periods
n = 2 # locations
j = 2 # industries
i = n # locations = n for 3 to 4 dim variables
k = j # industries = j for 3 to 4 dim variables

2

In [2]:
μ = Array{Float64}(undef, n, j, i, k, nl+1) # migration shares
π_0 = Array{Float64}(undef, n, j, i, j, nl+1) # cross-expenditures
β = 0.8
ν = 1.1

1.1

In [3]:
using Random
Random.seed!(1)

TaskLocalRNG()

In [4]:
for x in 1:n
    for y in 1:j
        matrix = rand(i, k)
        matrix2 = matrix/sum(matrix)
        μ[x, y, :, :, 1] = matrix2
    end
end
μ[:, :, :, :, 1]

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.0419308  0.344161
 0.359995   0.203362

[:, :, 2, 1] =
 0.199601   0.0725269
 0.0900771  0.000908277

[:, :, 1, 2] =
 0.399398  0.289712
 0.306728  0.381414

[:, :, 2, 2] =
 0.35907   0.293601
 0.243201  0.414316

In [5]:
for x in 1:n
    for y in 1:j
        matrix = rand(i, k)
        matrix2 = matrix/sum(matrix)
        π_0[x, y, :, :, 1] = matrix2
    end
end
π_0[:, :, :, :, 1]

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.308254  0.238938
 0.187336  0.354732

[:, :, 2, 1] =
 0.0196254  0.272704
 0.341713   0.298983

[:, :, 1, 2] =
 0.491333  0.118526
 0.141249  0.17604

[:, :, 2, 2] =
 0.180788  0.369832
 0.329702  0.170244

In [6]:
κdot = rand(0.92:0.001:1.08, (n, j, i, k, nl+1))

2×2×2×2×101 Array{Float64, 5}:
[:, :, 1, 1, 1] =
 1.049  0.975
 1.026  1.045

[:, :, 2, 1, 1] =
 0.951  0.921
 0.99   1.08

[:, :, 1, 2, 1] =
 1.025  1.053
 0.988  0.983

[:, :, 2, 2, 1] =
 0.99   0.929
 0.938  1.075

[:, :, 1, 1, 2] =
 0.963  1.03
 1.021  0.934

[:, :, 2, 1, 2] =
 1.008  1.007
 0.942  1.044

[:, :, 1, 2, 2] =
 1.027  1.065
 1.029  1.049

[:, :, 2, 2, 2] =
 1.045  0.939
 1.022  0.985

[:, :, 1, 1, 3] =
 1.017  0.953
 1.047  0.96

[:, :, 2, 1, 3] =
 0.966  1.079
 1.067  1.048

[:, :, 1, 2, 3] =
 0.927  1.036
 0.985  1.055

[:, :, 2, 2, 3] =
 0.931  1.078
 1.054  1.048

;;;;; … 

[:, :, 1, 1, 99] =
 1.08   1.022
 0.978  1.025

[:, :, 2, 1, 99] =
 0.988  0.968
 1.056  1.051

[:, :, 1, 2, 99] =
 0.997  1.005
 1.061  1.046

[:, :, 2, 2, 99] =
 1.038  0.961
 0.947  0.998

[:, :, 1, 1, 100] =
 1.05  1.025
 1.02  0.961

[:, :, 2, 1, 100] =
 0.948  1.066
 1.071  0.997

[:, :, 1, 2, 100] =
 0.941  0.973
 1.011  1.01

[:, :, 2, 2, 100] =
 1.047  1.028
 0.986  1.033

[:, :, 1, 1, 

In [7]:
Ȧ = rand(0.98:0.001:1.02, (n, j, nl+1))

2×2×101 Array{Float64, 3}:
[:, :, 1] =
 1.004  0.982
 0.984  0.986

[:, :, 2] =
 1.007  1.008
 0.994  0.999

[:, :, 3] =
 1.001  0.981
 1.014  0.985

;;; … 

[:, :, 99] =
 0.98   1.0
 0.989  1.014

[:, :, 100] =
 0.987  0.993
 0.992  0.998

[:, :, 101] =
 0.998  0.981
 0.996  1.018

In [8]:
L = Array{Float64}(undef, n, j, nl+1)
L_setup_matrix = rand(n, j)
L[:, :, 1] = L_setup_matrix/sum(L_setup_matrix)

2×2 Matrix{Float64}:
 0.25007  0.155137
 0.3511   0.243693

In [9]:
w = Array{Float64}(undef, n, j, nl+1)
w[:, :, 1] = rand(0.5:0.001:1.5, (n, j))

2×2 Matrix{Float64}:
 1.179  1.403
 1.365  1.124

In [10]:
using Distributions
θ_var = Frechet()
θ_list = rand(θ_var, (n, nl+1))

2×101 Matrix{Float64}:
 2.82569     1.23445   0.828066  1.78571  …  0.884455  1.70148  0.43028
 0.674978  105.765    18.0888    2.2091      4.53019   3.58693  1.14706

In [11]:
u̇_0t = ones(n, j, nl+1)

2×2×101 Array{Float64, 3}:
[:, :, 1] =
 1.0  1.0
 1.0  1.0

[:, :, 2] =
 1.0  1.0
 1.0  1.0

[:, :, 3] =
 1.0  1.0
 1.0  1.0

;;; … 

[:, :, 99] =
 1.0  1.0
 1.0  1.0

[:, :, 100] =
 1.0  1.0
 1.0  1.0

[:, :, 101] =
 1.0  1.0
 1.0  1.0

In [12]:
ẇ = ones(n, j, nl+1)

2×2×101 Array{Float64, 3}:
[:, :, 1] =
 1.0  1.0
 1.0  1.0

[:, :, 2] =
 1.0  1.0
 1.0  1.0

[:, :, 3] =
 1.0  1.0
 1.0  1.0

;;; … 

[:, :, 99] =
 1.0  1.0
 1.0  1.0

[:, :, 100] =
 1.0  1.0
 1.0  1.0

[:, :, 101] =
 1.0  1.0
 1.0  1.0

In [13]:
ẇn = Array{Float64}(undef, n, j, nl+1)
Ṗ = Array{Float64}(undef, n, j, nl+1)
X = Array{Float64}(undef, n, j, nl+1)
α = Array{Float64}(undef, j, nl+1)
ẇ_old = Array{Float64}(undef, n, j, nl+1)
u̇_0t_old = Array{Float64}(undef, n, j, nl+1)
u̇_1t = Array{Float64}(undef, n, j, nl+1)

2×2×101 Array{Float64, 3}:
[:, :, 1] =
 8.48409e-251  4.87111e-163
 3.64536e-158  2.3991e-236

[:, :, 2] =
 3.8101e-149   1.7113e-158
 1.71086e-158  2.01829e-265

[:, :, 3] =
 4.02153e-87   NaN
 9.49217e-270    5.01536e-293

;;; … 

[:, :, 99] =
 0.0  0.0
 0.0  0.0

[:, :, 100] =
 0.0  0.0
 0.0  0.0

[:, :, 101] =
 0.0  0.0
 0.0  0.0

In [16]:
#while !all(0.95 .*u̇_0t[:, :, t] .<= u̇_0t_old[:, :, t] .<= 1.05.*u̇_0t[:, :, t] for t in 1:nl+1 & 0.95.*ones(n, j).<= u̇_0t[:, :, nl+1] .<= 1.05.*ones(n, j))
while !(all(all(0.95 .*u̇_0t[:, :, t] .<= u̇_0t_old[:, :, t] .<= 1.05.*u̇_0t[:, :, t]) for t in 1:nl+1) & all(0.95.*ones(n, j) .<= u̇_0t[:, :, nl+1] .<= 1.05.*ones(n, j)))
    println("OUTER LOOP STARTS")
    u̇_0t_old .= deepcopy(u̇_0t)
    for t in 2:nl
        for a in 1:n
            for b in 1:j
                for c in 1:i
                    for d in 1:k
                        denom = sum(μ[a, b, m, h, t-1]*((u̇_0t[m, h, t+1])^(β/ν)) for m in 1:n, h in 1:j)
                        numer = (μ[a, b, c, d, t-1]*((u̇_0t[c, d, t+1])^(β/ν)))
                        μ[a, b, c, d, t] = numer/denom
                    end
                end
            end
        end
    end
    for t in 2:nl+1
        for a in 1:n
            for b in 1:j
                L[a, b, t] = sum(μ[c, d, a, b, t]*L[c, d, t-1] for c in 1:i, d in 1:k)
            end
        end
    end
    while !all(0.95*ẇ .<= ẇ_old .<= 1.05*ẇ)
        println("inner loop starts")
        ẇ_old .= deepcopy(ẇ)
        for t in 2:nl+1
            for a in 1:n
                for b in 1:j
                    for c in 1:i
                        Ṗ[n, j, t] = (sum(π_0[a, b, c, b, t]*((ẇ[c, b, t]*κdot[a, b, c, b, t])^(-θ_list[b, t]))*((Ȧ[c, b, t])^θ_list[b, t]) for c in 1:i))^(-1/θ_list[b, t])   
                    end
                end
            end
        end
        for t in 2:nl+1
            for a in 1:n
                for c in 1:i
                    for b in 1:j
                        π_0[a, b, c, b, t] = π_0[a, b, c, b]*(((ẇ[c, b]*κdot[a, b, c, b])/Ṗ[a, b])^(-θ_list[b]))*((Ȧ[c,b])^θ_list[b])
                    end
                end
            end  
        end
        for t in 1:nl+1
            for a in 1:n
                for b in 1:j
                    X[n, j, t] = w[n, j, t]*L[n, j, t]
                end
            end
        end
                    
        for t in 1:nl+1
            for b in 1:j
                α[b, t] = sum(X[k, b, t] for k in 1:n)/sum(X[j, l, t] for j in 1:n, l in 1:j)
            end
        end
        
        for t in 2:nl+1
            for a in 1:n
                for b in 1:j
                    w[a, b, t] = w[a, b, t-1]*ẇ[a, b, t]
                end
            end
        end
        
        for t in 1:nl+1
            for a in 1:n
                for b in 1:j
                    ẇn[a, b, t] = sum(π_0[c, b, a, b, t]*X[c, b, t] for c in 1:i)/(L[a, b, t]*w[a, b, t])
                end
            end
        end
        
        ẇ .= ẇn
        println("inner loop ends")
    end
    for t in 1:nl-1
        for a in 1:n
            for b in 1:j
                u̇_1t[a, b, t+1] = ẇ[a, b, t+1]*((sum(μ[a, b, c, d, t]*(u̇_0t[c, d, t+2])^(β/ν) for c in 1:i, d in 1:k))^(ν))
            end
        end
    end
    u̇_1t[:, :, nl+1] = ones(n, j)  # Discuss this with Professor Alder
    u̇_0t .= u̇_1t
    println("OUTER LOOP ENDS")
end

OUTER LOOP STARTS
inner loop starts


LoadError: DomainError with -5.229221971032956e282:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.